2023-11-07 22:29:32,597 : WARN  : comm-pool-thread-1 :  : Node : CSV Reader : 3:1 : Please specify a file
2023-11-07 22:29:45,257 : WARN  : comm-pool-thread-2 :  : Node : DB Connector : 3:2 : Please select a database type.
2023-11-08 00:16:54,480 : WARN  : main :  : Node : DB Insert : 3:3 : Configure node and enter a valid table name.
2023-11-08 00:17:33,598 : WARN  : main :  : Node : DB Insert : 3:3 : Configure node and enter a valid table name.
2023-11-08 00:17:34,047 : WARN  : main :  : Node : DB Insert : 3:3 : Configure node and enter a valid table name.
2023-11-08 00:20:57,033 : WARN  : KNIME-Worker-4-DB Connector 3:2 :  : Node : DB Insert : 3:3 : Configure node and enter a valid table name.
2023-11-08 00:21:01,861 : WARN  : SwingWorker-pool-7-thread-9 :  : ManagedConnection : DB Insert : 3:3 : 5 statements have not been closed before the closure of the managed connection.
2023-11-08 00:22:37,816 : WARN  : comm-pool-thread-9 :  : Node : CSV Reader : 3:7 : Please specify a file
2023-11-08 00:22:39,267 : WARN  : comm-pool-thread-9 :  : Node : CSV Reader : 3:8 : Please specify a file
2023-11-08 00:22:40,683 : WARN  : comm-pool-thread-9 :  : Node : CSV Reader : 3:9 : Please specify a file
2023-11-08 00:23:39,150 : WARN  : comm-pool-thread-9 :  : Node : DB Insert : 3:4 : Configure node and enter a valid table name.
2023-11-08 00:23:57,273 : ERROR : KNIME-Worker-8-DB Insert 3:4 :  : Node : DB Insert : 3:4 : Execute failed: Batch entry 15 INSERT INTO "sttrthie"."kunde" ("k_id", "k_name", "k_wohnort", "k_strasse", "k_geschlecht", "k_kundengruppe") VALUES (15,NULL,'Porta Westfalica','Kirchgasse 249','w','Privat') was aborted: ERROR: duplicate key value violates unique constraint "pk_kunde"
  Detail: Key (k_id)=(15) already exists.  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 15 INSERT INTO "sttrthie"."kunde" ("k_id", "k_name", "k_wohnort", "k_strasse", "k_geschlecht", "k_kundengruppe") VALUES (15,NULL,'Porta Westfalica','Kirchgasse 249','w','Privat') was aborted: ERROR: duplicate key value violates unique constraint "pk_kunde"
  Detail: Key (k_id)=(15) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.impl.monitored.MonitoredPreparedStatement.executeBatch(MonitoredPreparedStatement.java:102)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeBatchAndSendStatuses(DefaultDatabaseWriterExecutor.java:321)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeLeftOverRows(DefaultDatabaseWriterExecutor.java:401)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeInBatchMode(DefaultDatabaseWriterExecutor.java:267)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.execute(DefaultDatabaseWriterExecutor.java:99)
	at org.knime.database.agent.writer.impl.DefaultDBWriter.insert(DefaultDBWriter.java:224)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:93)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:1)
	at org.knime.database.node.io.DBManipulationNodeModel.executeStreamable(DBManipulationNodeModel.java:412)
	at org.knime.database.node.io.DBManipulationNodeModel.execute(DBManipulationNodeModel.java:346)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:558)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1274)
	at org.knime.core.node.Node.execute(Node.java:1036)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:595)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:98)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_kunde"
  Detail: Key (k_id)=(15) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 30 more
2023-11-08 00:23:58,946 : ERROR : KNIME-Worker-9-DB Insert 3:4 :  : Node : DB Insert : 3:4 : Execute failed: Batch entry 15 INSERT INTO "sttrthie"."kunde" ("k_id", "k_name", "k_wohnort", "k_strasse", "k_geschlecht", "k_kundengruppe") VALUES (15,NULL,'Porta Westfalica','Kirchgasse 249','w','Privat') was aborted: ERROR: duplicate key value violates unique constraint "pk_kunde"
  Detail: Key (k_id)=(15) already exists.  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 15 INSERT INTO "sttrthie"."kunde" ("k_id", "k_name", "k_wohnort", "k_strasse", "k_geschlecht", "k_kundengruppe") VALUES (15,NULL,'Porta Westfalica','Kirchgasse 249','w','Privat') was aborted: ERROR: duplicate key value violates unique constraint "pk_kunde"
  Detail: Key (k_id)=(15) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.impl.monitored.MonitoredPreparedStatement.executeBatch(MonitoredPreparedStatement.java:102)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeBatchAndSendStatuses(DefaultDatabaseWriterExecutor.java:321)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeLeftOverRows(DefaultDatabaseWriterExecutor.java:401)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeInBatchMode(DefaultDatabaseWriterExecutor.java:267)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.execute(DefaultDatabaseWriterExecutor.java:99)
	at org.knime.database.agent.writer.impl.DefaultDBWriter.insert(DefaultDBWriter.java:224)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:93)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:1)
	at org.knime.database.node.io.DBManipulationNodeModel.executeStreamable(DBManipulationNodeModel.java:412)
	at org.knime.database.node.io.DBManipulationNodeModel.execute(DBManipulationNodeModel.java:346)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:558)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1274)
	at org.knime.core.node.Node.execute(Node.java:1036)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:595)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:98)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_kunde"
  Detail: Key (k_id)=(15) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 30 more
2023-11-08 00:24:50,895 : ERROR : KNIME-Worker-7-DB Insert 3:4 :  : Node : DB Insert : 3:4 : Execute failed: Batch entry 15 INSERT INTO "sttrthie"."kunde" ("k_id", "k_name", "k_wohnort", "k_strasse", "k_geschlecht", "k_kundengruppe") VALUES (15,NULL,'Porta Westfalica','Kirchgasse 249','w','Privat') was aborted: ERROR: duplicate key value violates unique constraint "pk_kunde"
  Detail: Key (k_id)=(15) already exists.  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 15 INSERT INTO "sttrthie"."kunde" ("k_id", "k_name", "k_wohnort", "k_strasse", "k_geschlecht", "k_kundengruppe") VALUES (15,NULL,'Porta Westfalica','Kirchgasse 249','w','Privat') was aborted: ERROR: duplicate key value violates unique constraint "pk_kunde"
  Detail: Key (k_id)=(15) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.impl.monitored.MonitoredPreparedStatement.executeBatch(MonitoredPreparedStatement.java:102)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeBatchAndSendStatuses(DefaultDatabaseWriterExecutor.java:321)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeLeftOverRows(DefaultDatabaseWriterExecutor.java:401)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeInBatchMode(DefaultDatabaseWriterExecutor.java:267)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.execute(DefaultDatabaseWriterExecutor.java:99)
	at org.knime.database.agent.writer.impl.DefaultDBWriter.insert(DefaultDBWriter.java:224)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:93)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:1)
	at org.knime.database.node.io.DBManipulationNodeModel.executeStreamable(DBManipulationNodeModel.java:412)
	at org.knime.database.node.io.DBManipulationNodeModel.execute(DBManipulationNodeModel.java:346)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:558)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1274)
	at org.knime.core.node.Node.execute(Node.java:1036)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:595)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:98)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_kunde"
  Detail: Key (k_id)=(15) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 30 more
2023-11-08 00:26:32,982 : WARN  : main :  : Node : DB Insert : 3:5 : Configure node and enter a valid table name.
2023-11-08 00:26:33,265 : WARN  : main :  : Node : DB Insert : 3:5 : Configure node and enter a valid table name.
2023-11-08 00:26:35,936 : WARN  : KNIME-Worker-10-CSV Reader 3:9 :  : Node : DB Insert : 3:5 : Configure node and enter a valid table name.
2023-11-08 00:27:52,448 : WARN  : main :  : Node : DB Insert : 3:6 : Configure node and enter a valid table name.
2023-11-08 00:27:52,859 : WARN  : main :  : Node : DB Insert : 3:6 : Configure node and enter a valid table name.
2023-11-08 00:28:16,793 : WARN  : comm-pool-thread-13 :  : Node : CSV Reader : 3:10 : Please specify a file
2023-11-08 00:28:18,087 : WARN  : comm-pool-thread-13 :  : Node : CSV Reader : 3:11 : Please specify a file
2023-11-08 00:31:48,961 : WARN  : comm-pool-thread-15 :  : Node : DB Insert : 3:5 : Configure node and enter a valid table name.
2023-11-08 00:39:54,039 : WARN  : comm-pool-thread-16 :  : Node : Row Filter : 3:14 : No row filter specified
2023-11-08 00:40:25,721 : WARN  : main :  : Node : DB Insert : 3:5 : Configure node and enter a valid table name.
2023-11-08 00:40:26,510 : WARN  : main :  : Node : DB Insert : 3:5 : Configure node and enter a valid table name.
2023-11-08 00:40:29,925 : WARN  : KNIME-Worker-11-Row Filter 3:14 :  : Node : DB Insert : 3:5 : Configure node and enter a valid table name.
2023-11-08 00:40:33,779 : ERROR : KNIME-Worker-12-DB Insert 3:4 :  : Node : DB Insert : 3:4 : Execute failed: Batch entry 43 INSERT INTO "sttrthie"."kunde" ("k_id", "k_name", "k_wohnort", "k_strasse", "k_geschlecht", "k_kundengruppe") VALUES (43,'Uschi Bitufo','Augsburg','Fasanenweg 18','w','Privat') was aborted: ERROR: duplicate key value violates unique constraint "pk_kunde"
  Detail: Key (k_id)=(43) already exists.  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 43 INSERT INTO "sttrthie"."kunde" ("k_id", "k_name", "k_wohnort", "k_strasse", "k_geschlecht", "k_kundengruppe") VALUES (43,'Uschi Bitufo','Augsburg','Fasanenweg 18','w','Privat') was aborted: ERROR: duplicate key value violates unique constraint "pk_kunde"
  Detail: Key (k_id)=(43) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.impl.monitored.MonitoredPreparedStatement.executeBatch(MonitoredPreparedStatement.java:102)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeBatchAndSendStatuses(DefaultDatabaseWriterExecutor.java:321)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeLeftOverRows(DefaultDatabaseWriterExecutor.java:401)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeInBatchMode(DefaultDatabaseWriterExecutor.java:267)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.execute(DefaultDatabaseWriterExecutor.java:99)
	at org.knime.database.agent.writer.impl.DefaultDBWriter.insert(DefaultDBWriter.java:224)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:93)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:1)
	at org.knime.database.node.io.DBManipulationNodeModel.executeStreamable(DBManipulationNodeModel.java:412)
	at org.knime.database.node.io.DBManipulationNodeModel.execute(DBManipulationNodeModel.java:346)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:558)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1274)
	at org.knime.core.node.Node.execute(Node.java:1036)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:595)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:98)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_kunde"
  Detail: Key (k_id)=(43) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 30 more
2023-11-08 00:40:33,785 : WARN  : KNIME-Worker-12-DB Insert 3:4 :  : Node : DB Insert : 3:5 : Configure node and enter a valid table name.
2023-11-08 00:41:30,334 : WARN  : comm-pool-thread-18 :  : Node : DB Insert : 3:5 : Configure node and enter a valid table name.
2023-11-08 00:41:38,647 : WARN  : KNIME-Worker-13-Duplicate Row Filter 3:15 :  : Node : DB Insert : 3:5 : Configure node and enter a valid table name.
2023-11-08 00:41:42,289 : WARN  : KNIME-Worker-11-DB Insert 3:4 :  : Node : DB Insert : 3:5 : Configure node and enter a valid table name.
2023-11-08 00:44:58,899 : WARN  : main :  : Node : DB Insert : 3:6 : Configure node and enter a valid table name.
2023-11-08 00:44:59,224 : WARN  : main :  : Node : DB Insert : 3:6 : Configure node and enter a valid table name.
2023-11-08 00:45:00,276 : WARN  : KNIME-Worker-14-DB Insert 3:5 :  : Node : DB Insert : 3:6 : Configure node and enter a valid table name.
2023-11-08 00:45:04,046 : WARN  : KNIME-Worker-15-CSV Reader 3:8 :  : Node : DB Insert : 3:6 : Configure node and enter a valid table name.
2023-11-08 00:45:40,181 : WARN  : main :  : Node : DB Insert : 3:12 : Configure node and enter a valid table name.
2023-11-08 00:45:40,501 : WARN  : main :  : Node : DB Insert : 3:12 : Configure node and enter a valid table name.
2023-11-08 00:45:42,569 : WARN  : KNIME-Worker-14-CSV Reader 3:10 :  : Node : DB Insert : 3:12 : Configure node and enter a valid table name.
2023-11-08 00:46:11,300 : WARN  : main :  : Node : DB Insert : 3:13 : Configure node and enter a valid table name.
2023-11-08 00:46:11,628 : WARN  : main :  : Node : DB Insert : 3:13 : Configure node and enter a valid table name.
2023-11-08 00:46:12,815 : WARN  : KNIME-Worker-16-CSV Reader 3:11 :  : Node : DB Insert : 3:13 : Configure node and enter a valid table name.
2023-11-08 00:46:49,531 : WARN  : comm-pool-thread-19 :  : Node : Row Filter : 3:16 : No row filter specified
2023-11-08 00:47:20,657 : ERROR : KNIME-Worker-14-DB Insert 3:3 :  : Node : DB Insert : 3:3 : Execute failed: Batch entry 0 INSERT INTO "sttrthie"."fahrzeug" ("f_id", "f_bezeichnung", "f_typ", "f_kategorie") VALUES (1,'Toyota Auris','Kleinwagen','Hybrid') was aborted: ERROR: duplicate key value violates unique constraint "pk_fahrzeug"
  Detail: Key (f_id)=(1) already exists.  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "sttrthie"."fahrzeug" ("f_id", "f_bezeichnung", "f_typ", "f_kategorie") VALUES (1,'Toyota Auris','Kleinwagen','Hybrid') was aborted: ERROR: duplicate key value violates unique constraint "pk_fahrzeug"
  Detail: Key (f_id)=(1) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.impl.monitored.MonitoredPreparedStatement.executeBatch(MonitoredPreparedStatement.java:102)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeBatchAndSendStatuses(DefaultDatabaseWriterExecutor.java:321)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeLeftOverRows(DefaultDatabaseWriterExecutor.java:401)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeInBatchMode(DefaultDatabaseWriterExecutor.java:267)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.execute(DefaultDatabaseWriterExecutor.java:99)
	at org.knime.database.agent.writer.impl.DefaultDBWriter.insert(DefaultDBWriter.java:224)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:93)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:1)
	at org.knime.database.node.io.DBManipulationNodeModel.executeStreamable(DBManipulationNodeModel.java:412)
	at org.knime.database.node.io.DBManipulationNodeModel.execute(DBManipulationNodeModel.java:346)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:558)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1274)
	at org.knime.core.node.Node.execute(Node.java:1036)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:595)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:98)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_fahrzeug"
  Detail: Key (f_id)=(1) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 30 more
2023-11-08 00:47:22,226 : ERROR : KNIME-Worker-15-DB Insert 3:3 :  : Node : DB Insert : 3:3 : Execute failed: Batch entry 0 INSERT INTO "sttrthie"."fahrzeug" ("f_id", "f_bezeichnung", "f_typ", "f_kategorie") VALUES (1,'Toyota Auris','Kleinwagen','Hybrid') was aborted: ERROR: duplicate key value violates unique constraint "pk_fahrzeug"
  Detail: Key (f_id)=(1) already exists.  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "sttrthie"."fahrzeug" ("f_id", "f_bezeichnung", "f_typ", "f_kategorie") VALUES (1,'Toyota Auris','Kleinwagen','Hybrid') was aborted: ERROR: duplicate key value violates unique constraint "pk_fahrzeug"
  Detail: Key (f_id)=(1) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.impl.monitored.MonitoredPreparedStatement.executeBatch(MonitoredPreparedStatement.java:102)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeBatchAndSendStatuses(DefaultDatabaseWriterExecutor.java:321)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeLeftOverRows(DefaultDatabaseWriterExecutor.java:401)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeInBatchMode(DefaultDatabaseWriterExecutor.java:267)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.execute(DefaultDatabaseWriterExecutor.java:99)
	at org.knime.database.agent.writer.impl.DefaultDBWriter.insert(DefaultDBWriter.java:224)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:93)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:1)
	at org.knime.database.node.io.DBManipulationNodeModel.executeStreamable(DBManipulationNodeModel.java:412)
	at org.knime.database.node.io.DBManipulationNodeModel.execute(DBManipulationNodeModel.java:346)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:558)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1274)
	at org.knime.core.node.Node.execute(Node.java:1036)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:595)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:98)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_fahrzeug"
  Detail: Key (f_id)=(1) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 30 more
2023-11-08 00:48:12,155 : WARN  : main :  : WrappedNodeDialog : DB Query : 3:18 : failed to apply settings: Database view place holder (#table#) must not be replaced.
org.knime.core.node.InvalidSettingsException: Database view place holder (#table#) must not be replaced.
	at org.knime.database.node.manipulation.query.DBSQLQueryNodeModel.validateSettingsInternal(DBSQLQueryNodeModel.java:130)
	at org.knime.database.node.DBNodeModel.validateSettings(DBNodeModel.java:184)
	at org.knime.core.node.Node.validateModelSettings(Node.java:696)
	at org.knime.core.node.workflow.NativeNodeContainer.performValidateSettings(NativeNodeContainer.java:1184)
	at org.knime.core.node.workflow.SingleNodeContainer.validateSettings(SingleNodeContainer.java:1000)
	at org.knime.core.node.workflow.WorkflowManager.loadNodeSettings(WorkflowManager.java:2177)
	at org.knime.core.node.workflow.NodeContainer.applySettingsFromDialog(NodeContainer.java:1141)
	at org.knime.core.ui.wrapper.NodeContainerWrapper.applySettingsFromDialog(NodeContainerWrapper.java:264)
	at org.knime.workbench.ui.wrapper.WrappedNodeDialog.callApplySettingsFromDialog(WrappedNodeDialog.java:672)
	at org.knime.workbench.ui.wrapper.WrappedNodeDialog.doApply(WrappedNodeDialog.java:644)
	at org.knime.workbench.ui.wrapper.WrappedNodeDialog$6.widgetSelected(WrappedNodeDialog.java:510)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.knime.workbench.ui.wrapper.WrappedNodeDialog.open(WrappedNodeDialog.java:199)
	at org.knime.workbench.editor2.editparts.NodeContainerEditPart.openDialog(NodeContainerEditPart.java:957)
	at org.knime.workbench.editor2.editparts.NodeContainerEditPart.openNodeDialog(NodeContainerEditPart.java:864)
	at org.knime.ui.java.api.NodeAPI.openNodeDialog(NodeAPI.java:95)
	at jdk.internal.reflect.GeneratedMethodAccessor183.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.knime.ui.java.api.DesktopAPI.lambda$0(DesktopAPI.java:128)
	at org.knime.ui.java.browser.KnimeBrowserFunction.function(KnimeBrowserFunction.java:80)
	at com.equo.chromium.swt.internal.Chromium$FunctionsResourceHandler.lambda$0(Chromium.java:362)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.knime.product.rcp.KNIMEApplication.start(KNIMEApplication.java:193)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
2023-11-08 00:48:20,778 : WARN  : main :  : WrappedNodeDialog : DB Query : 3:18 : failed to apply settings: Database view place holder (#table#) must not be replaced.
org.knime.core.node.InvalidSettingsException: Database view place holder (#table#) must not be replaced.
	at org.knime.database.node.manipulation.query.DBSQLQueryNodeModel.validateSettingsInternal(DBSQLQueryNodeModel.java:130)
	at org.knime.database.node.DBNodeModel.validateSettings(DBNodeModel.java:184)
	at org.knime.core.node.Node.validateModelSettings(Node.java:696)
	at org.knime.core.node.workflow.NativeNodeContainer.performValidateSettings(NativeNodeContainer.java:1184)
	at org.knime.core.node.workflow.SingleNodeContainer.validateSettings(SingleNodeContainer.java:1000)
	at org.knime.core.node.workflow.WorkflowManager.loadNodeSettings(WorkflowManager.java:2177)
	at org.knime.core.node.workflow.NodeContainer.applySettingsFromDialog(NodeContainer.java:1141)
	at org.knime.core.ui.wrapper.NodeContainerWrapper.applySettingsFromDialog(NodeContainerWrapper.java:264)
	at org.knime.workbench.ui.wrapper.WrappedNodeDialog.callApplySettingsFromDialog(WrappedNodeDialog.java:672)
	at org.knime.workbench.ui.wrapper.WrappedNodeDialog.doApply(WrappedNodeDialog.java:644)
	at org.knime.workbench.ui.wrapper.WrappedNodeDialog.doOK(WrappedNodeDialog.java:559)
	at org.knime.workbench.ui.wrapper.WrappedNodeDialog$5.widgetSelected(WrappedNodeDialog.java:495)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.knime.workbench.ui.wrapper.WrappedNodeDialog.open(WrappedNodeDialog.java:199)
	at org.knime.workbench.editor2.editparts.NodeContainerEditPart.openDialog(NodeContainerEditPart.java:957)
	at org.knime.workbench.editor2.editparts.NodeContainerEditPart.openNodeDialog(NodeContainerEditPart.java:864)
	at org.knime.ui.java.api.NodeAPI.openNodeDialog(NodeAPI.java:95)
	at jdk.internal.reflect.GeneratedMethodAccessor183.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.knime.ui.java.api.DesktopAPI.lambda$0(DesktopAPI.java:128)
	at org.knime.ui.java.browser.KnimeBrowserFunction.function(KnimeBrowserFunction.java:80)
	at com.equo.chromium.swt.internal.Chromium$FunctionsResourceHandler.lambda$0(Chromium.java:362)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.knime.product.rcp.KNIMEApplication.start(KNIMEApplication.java:193)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
2023-11-08 00:49:45,095 : WARN  : comm-pool-thread-22 :  : Node : Row Filter : 3:18 : Column range filter: Input table doesn't contain specified column name
2023-11-08 00:50:18,801 : WARN  : comm-pool-thread-22 :  : Node : Row Filter : 3:20 : Column range filter: Input table doesn't contain specified column name
2023-11-08 00:50:30,480 : WARN  : comm-pool-thread-22 :  : Node : Row Filter : 3:22 : Column range filter: Input table doesn't contain specified column name
2023-11-08 00:50:42,866 : WARN  : comm-pool-thread-22 :  : Node : Row Filter : 3:24 : Column range filter: Input table doesn't contain specified column name
2023-11-08 00:51:07,233 : ERROR : KNIME-Worker-23-DB Insert 3:5 :  : Node : DB Insert : 3:5 : Execute failed: Batch entry 0 INSERT INTO "sttrthie"."ort" ("o_id", "o_filiale", "o_stadt", "o_bundesland", "o_land") VALUES (1,'Autohaus Brass','Darmstadt','Hessen','Deutschland') was aborted: ERROR: duplicate key value violates unique constraint "pk_ort"
  Detail: Key (o_id)=(1) already exists.  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "sttrthie"."ort" ("o_id", "o_filiale", "o_stadt", "o_bundesland", "o_land") VALUES (1,'Autohaus Brass','Darmstadt','Hessen','Deutschland') was aborted: ERROR: duplicate key value violates unique constraint "pk_ort"
  Detail: Key (o_id)=(1) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.impl.monitored.MonitoredPreparedStatement.executeBatch(MonitoredPreparedStatement.java:102)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeBatchAndSendStatuses(DefaultDatabaseWriterExecutor.java:321)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeLeftOverRows(DefaultDatabaseWriterExecutor.java:401)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeInBatchMode(DefaultDatabaseWriterExecutor.java:267)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.execute(DefaultDatabaseWriterExecutor.java:99)
	at org.knime.database.agent.writer.impl.DefaultDBWriter.insert(DefaultDBWriter.java:224)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:93)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:1)
	at org.knime.database.node.io.DBManipulationNodeModel.executeStreamable(DBManipulationNodeModel.java:412)
	at org.knime.database.node.io.DBManipulationNodeModel.execute(DBManipulationNodeModel.java:346)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:558)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1274)
	at org.knime.core.node.Node.execute(Node.java:1036)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:595)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:98)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_ort"
  Detail: Key (o_id)=(1) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 30 more
2023-11-08 00:51:21,235 : ERROR : KNIME-Worker-22-DB Insert 3:13 :  : Node : DB Insert : 3:13 : Execute failed: Batch entry 0 INSERT INTO "sttrthie"."verkauf" ("vk_id", "o_id", "f_id", "v_id", "k_id", "z_id", "vk_umsatz") VALUES (1,33,5,2,64,63,51340) was aborted: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_fahrzeug"
  Detail: Key (f_id)=(5) is not present in table "fahrzeug".  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "sttrthie"."verkauf" ("vk_id", "o_id", "f_id", "v_id", "k_id", "z_id", "vk_umsatz") VALUES (1,33,5,2,64,63,51340) was aborted: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_fahrzeug"
  Detail: Key (f_id)=(5) is not present in table "fahrzeug".  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1297)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1322)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:465)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.impl.monitored.MonitoredPreparedStatement.executeBatch(MonitoredPreparedStatement.java:102)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeBatchAndSendStatuses(DefaultDatabaseWriterExecutor.java:321)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeLeftOverRows(DefaultDatabaseWriterExecutor.java:401)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeInBatchMode(DefaultDatabaseWriterExecutor.java:267)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.execute(DefaultDatabaseWriterExecutor.java:99)
	at org.knime.database.agent.writer.impl.DefaultDBWriter.insert(DefaultDBWriter.java:224)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:93)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:1)
	at org.knime.database.node.io.DBManipulationNodeModel.executeStreamable(DBManipulationNodeModel.java:412)
	at org.knime.database.node.io.DBManipulationNodeModel.execute(DBManipulationNodeModel.java:346)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:558)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1274)
	at org.knime.core.node.Node.execute(Node.java:1036)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:595)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:98)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_fahrzeug"
  Detail: Key (f_id)=(5) is not present in table "fahrzeug".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 32 more
2023-11-08 00:52:04,608 : ERROR : KNIME-Worker-23-DB Insert 3:13 :  : Node : DB Insert : 3:13 : Execute failed: Batch entry 0 INSERT INTO "sttrthie"."verkauf" ("vk_id", "o_id", "f_id", "v_id", "k_id", "z_id", "vk_umsatz") VALUES (1,33,5,2,64,63,51340) was aborted: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_fahrzeug"
  Detail: Key (f_id)=(5) is not present in table "fahrzeug".  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "sttrthie"."verkauf" ("vk_id", "o_id", "f_id", "v_id", "k_id", "z_id", "vk_umsatz") VALUES (1,33,5,2,64,63,51340) was aborted: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_fahrzeug"
  Detail: Key (f_id)=(5) is not present in table "fahrzeug".  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1297)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1322)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:465)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.impl.monitored.MonitoredPreparedStatement.executeBatch(MonitoredPreparedStatement.java:102)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeBatchAndSendStatuses(DefaultDatabaseWriterExecutor.java:321)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeLeftOverRows(DefaultDatabaseWriterExecutor.java:401)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeInBatchMode(DefaultDatabaseWriterExecutor.java:267)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.execute(DefaultDatabaseWriterExecutor.java:99)
	at org.knime.database.agent.writer.impl.DefaultDBWriter.insert(DefaultDBWriter.java:224)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:93)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:1)
	at org.knime.database.node.io.DBManipulationNodeModel.executeStreamable(DBManipulationNodeModel.java:412)
	at org.knime.database.node.io.DBManipulationNodeModel.execute(DBManipulationNodeModel.java:346)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:558)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1274)
	at org.knime.core.node.Node.execute(Node.java:1036)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:595)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:98)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_fahrzeug"
  Detail: Key (f_id)=(5) is not present in table "fahrzeug".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 32 more
2023-11-08 00:52:19,187 : ERROR : KNIME-Worker-21-DB Insert 3:13 :  : Node : DB Insert : 3:13 : Execute failed: Batch entry 0 INSERT INTO "sttrthie"."verkauf" ("vk_id", "o_id", "f_id", "v_id", "k_id", "z_id", "vk_umsatz") VALUES (1,33,5,2,64,63,51340) was aborted: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_ort"
  Detail: Key (o_id)=(33) is not present in table "ort".  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "sttrthie"."verkauf" ("vk_id", "o_id", "f_id", "v_id", "k_id", "z_id", "vk_umsatz") VALUES (1,33,5,2,64,63,51340) was aborted: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_ort"
  Detail: Key (o_id)=(33) is not present in table "ort".  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1297)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1322)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:465)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.impl.monitored.MonitoredPreparedStatement.executeBatch(MonitoredPreparedStatement.java:102)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeBatchAndSendStatuses(DefaultDatabaseWriterExecutor.java:321)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeLeftOverRows(DefaultDatabaseWriterExecutor.java:401)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeInBatchMode(DefaultDatabaseWriterExecutor.java:267)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.execute(DefaultDatabaseWriterExecutor.java:99)
	at org.knime.database.agent.writer.impl.DefaultDBWriter.insert(DefaultDBWriter.java:224)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:93)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:1)
	at org.knime.database.node.io.DBManipulationNodeModel.executeStreamable(DBManipulationNodeModel.java:412)
	at org.knime.database.node.io.DBManipulationNodeModel.execute(DBManipulationNodeModel.java:346)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:558)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1274)
	at org.knime.core.node.Node.execute(Node.java:1036)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:595)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:98)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_ort"
  Detail: Key (o_id)=(33) is not present in table "ort".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 32 more
2023-11-08 00:52:47,973 : ERROR : KNIME-Worker-20-DB Insert 3:13 :  : Node : DB Insert : 3:13 : Execute failed: Batch entry 0 INSERT INTO "sttrthie"."verkauf" ("vk_id", "o_id", "f_id", "v_id", "k_id", "z_id", "vk_umsatz") VALUES (1,33,5,2,64,63,51340) was aborted: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_ort"
  Detail: Key (o_id)=(33) is not present in table "ort".  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "sttrthie"."verkauf" ("vk_id", "o_id", "f_id", "v_id", "k_id", "z_id", "vk_umsatz") VALUES (1,33,5,2,64,63,51340) was aborted: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_ort"
  Detail: Key (o_id)=(33) is not present in table "ort".  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1297)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1322)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:465)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.impl.monitored.MonitoredPreparedStatement.executeBatch(MonitoredPreparedStatement.java:102)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeBatchAndSendStatuses(DefaultDatabaseWriterExecutor.java:321)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeLeftOverRows(DefaultDatabaseWriterExecutor.java:401)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeInBatchMode(DefaultDatabaseWriterExecutor.java:267)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.execute(DefaultDatabaseWriterExecutor.java:99)
	at org.knime.database.agent.writer.impl.DefaultDBWriter.insert(DefaultDBWriter.java:224)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:93)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:1)
	at org.knime.database.node.io.DBManipulationNodeModel.executeStreamable(DBManipulationNodeModel.java:412)
	at org.knime.database.node.io.DBManipulationNodeModel.execute(DBManipulationNodeModel.java:346)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:558)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1274)
	at org.knime.core.node.Node.execute(Node.java:1036)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:595)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:98)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_ort"
  Detail: Key (o_id)=(33) is not present in table "ort".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 32 more
2023-11-08 00:52:48,585 : ERROR : KNIME-Worker-24-DB Insert 3:13 :  : Node : DB Insert : 3:13 : Execute failed: Batch entry 0 INSERT INTO "sttrthie"."verkauf" ("vk_id", "o_id", "f_id", "v_id", "k_id", "z_id", "vk_umsatz") VALUES (1,33,5,2,64,63,51340) was aborted: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_ort"
  Detail: Key (o_id)=(33) is not present in table "ort".  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "sttrthie"."verkauf" ("vk_id", "o_id", "f_id", "v_id", "k_id", "z_id", "vk_umsatz") VALUES (1,33,5,2,64,63,51340) was aborted: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_ort"
  Detail: Key (o_id)=(33) is not present in table "ort".  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1297)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1322)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:465)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.connection.impl.monitored.MonitoredPreparedStatement.executeBatch(MonitoredPreparedStatement.java:102)
	at org.knime.database.connection.wrappers.AbstractStatementWrapper.executeBatch(AbstractStatementWrapper.java:229)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeBatchAndSendStatuses(DefaultDatabaseWriterExecutor.java:321)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeLeftOverRows(DefaultDatabaseWriterExecutor.java:401)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.executeInBatchMode(DefaultDatabaseWriterExecutor.java:267)
	at org.knime.database.agent.writer.impl.DefaultDatabaseWriterExecutor.execute(DefaultDatabaseWriterExecutor.java:99)
	at org.knime.database.agent.writer.impl.DefaultDBWriter.insert(DefaultDBWriter.java:224)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:93)
	at org.knime.database.node.io.insert.DBInsertNodeModel.executeWriter(DBInsertNodeModel.java:1)
	at org.knime.database.node.io.DBManipulationNodeModel.executeStreamable(DBManipulationNodeModel.java:412)
	at org.knime.database.node.io.DBManipulationNodeModel.execute(DBManipulationNodeModel.java:346)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:558)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1274)
	at org.knime.core.node.Node.execute(Node.java:1036)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:595)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:98)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "verkauf" violates foreign key constraint "fk_verkauf_reference_ort"
  Detail: Key (o_id)=(33) is not present in table "ort".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 32 more
2023-11-09 05:20:21,913 : WARN  : ModalContext :  : Node : DB Connector : 3:2 : DB Connection no longer available. Go to advanced settings to enable connection restoration.
